@startuml operator-components
'Icons
''!include <kubernetes/k8s-sprites-unlabeled-25pct>
!theme spacelab

skinparam componentStyle rectangle
'mainframe **Operator Components**
rectangle " " as operator {

    component "Custom Resource" as custom_resource
    component "CRD" as crd
    component "Controller" as controller

}

@enduml
