@startuml operator-components
'Icons
!include <kubernetes/k8s-sprites-unlabeled-25pct>

'Style
skinparam componentBackgroundColor white
skinparam rectangleBackgroundColor white
skinparam componentStyle rectangle
skinparam nodesep 75

rectangle "Kubernetes cluster" as operator {

    node "Worker nodes" as nodes {

        component "\t<color:darkblue><$deploy></color>\nCustom Controller" as controller
        together {
            component "<color:darkblue><$crd></color>\n   CRD" as crd
            component "\t<color:darkblue><$pod></color>\nCustom Resource" as custom_resource
        }
    }
    node "Control Plane" as control {

        component "\t<color:darkblue><$deploy></color>\nController Manager" as k8s_controllerManager
    }
}

'Relations'
crd ..> custom_resource : Defines
k8s_controllerManager -> controller : Reconcliles
controller -> custom_resource : Observes
@enduml
